package muddy.top.wechatdemo.Utils;

/**
 * @Author Muddy
 * @Time 2018/9/17
 * @Describe
 */
public class CityClass {
    public static final String cityAndNum="[\n" +
            "{\"Country\":\"马来西亚\",\"AreaCode\":\"0060\"},\n" +
            "{\"Country\":\"印度尼西亚\",\"AreaCode\":\"0062\"},\n" +
            "{\"Country\":\"菲律宾\",\"AreaCode\":\"0063\"},\n" +
            "{\"Country\":\"新加坡\",\"AreaCode\":\"0065\"},\n" +
            "{\"Country\":\"泰国\",\"AreaCode\":\"0066\"},\n" +
            "{\"Country\":\"文莱\",\"AreaCode\":\"00673\"},\n" +
            "{\"Country\":\"日本\",\"AreaCode\":\"0081\"},\n" +
            "{\"Country\":\"韩国\",\"AreaCode\":\"0082\"},\n" +
            "{\"Country\":\"越南\",\"AreaCode\":\"0084\"},\n" +
            "{\"Country\":\"朝鲜\",\"AreaCode\":\"00850\"},\n" +
            "{\"Country\":\"香港\",\"AreaCode\":\"00852\"},\n" +
            "{\"Country\":\"澳门\",\"AreaCode\":\"00853\"},\n" +
            "{\"Country\":\"柬埔寨\",\"AreaCode\":\"00855\"},\n" +
            "{\"Country\":\"老挝\",\"AreaCode\":\"00856\"},\n" +
            "{\"Country\":\"中国\",\"AreaCode\":\"0086\"},\n" +
            "{\"Country\":\"台湾\",\"AreaCode\":\"00886\"},\n" +
            "{\"Country\":\"孟加拉国\",\"AreaCode\":\"00880\"},\n" +
            "{\"Country\":\"土耳其\",\"AreaCode\":\"0090\"},\n" +
            "{\"Country\":\"印度\",\"AreaCode\":\"0091\"},\n" +
            "{\"Country\":\"巴基斯坦\",\"AreaCode\":\"0092\"},\n" +
            "{\"Country\":\"阿富汗\",\"AreaCode\":\"0093\"},\n" +
            "{\"Country\":\"斯里兰卡\",\"AreaCode\":\"0094\"},\n" +
            "{\"Country\":\"缅甸\",\"AreaCode\":\"0095\"},\n" +
            "{\"Country\":\"马尔代夫\",\"AreaCode\":\"00960\"},\n" +
            "{\"Country\":\"黎巴嫩\",\"AreaCode\":\"00961\"},\n" +
            "{\"Country\":\"约旦\",\"AreaCode\":\"00962\"},\n" +
            "{\"Country\":\"叙利亚\",\"AreaCode\":\"00963\"},\n" +
            "{\"Country\":\"伊拉克\",\"AreaCode\":\"00964\"},\n" +
            "{\"Country\":\"科威特\",\"AreaCode\":\"00965\"},\n" +
            "{\"Country\":\"沙特阿拉伯\",\"AreaCode\":\"00966\"},\n" +
            "{\"Country\":\"阿曼\",\"AreaCode\":\"00968\"},\n" +
            "{\"Country\":\"以色列\",\"AreaCode\":\"00972\"},\n" +
            "{\"Country\":\"巴林\",\"AreaCode\":\"00973\"},\n" +
            "{\"Country\":\"卡塔尔\",\"AreaCode\":\"00974\"},\n" +
            "{\"Country\":\"不丹\",\"AreaCode\":\"00975\"},\n" +
            "{\"Country\":\"蒙古\",\"AreaCode\":\"00976\"},\n" +
            "{\"Country\":\"尼泊尔\",\"AreaCode\":\"00977\"},\n" +
            "{\"Country\":\"伊朗\",\"AreaCode\":\"0098\"},\n" +
            "{\"Country\":\"俄罗斯\",\"AreaCode\":\"007\"},\n" +
            "{\"Country\":\"希腊\",\"AreaCode\":\"0030\"},\n" +
            "{\"Country\":\"荷兰\",\"AreaCode\":\"0031\"},\n" +
            "{\"Country\":\"比利时\",\"AreaCode\":\"0032\"},\n" +
            "{\"Country\":\"法国\",\"AreaCode\":\"0033\",},\n" +
            "{\"Country\":\"西班牙\",\"AreaCode\":\"0034\"},\n" +
            "{\"Country\":\"直布罗陀\",\"AreaCode\":\"00350\"},\n" +
            "{\"Country\":\"葡萄牙\",\"AreaCode\":\"00351\"},\n" +
            "{\"Country\":\"卢森堡\",\"AreaCode\":\"00352\"},\n" +
            "{\"Country\":\"爱尔兰\",\"AreaCode\":\"00353\"},\n" +
            "{\"Country\":\"冰岛\",\"AreaCode\":\"00354\"},\n" +
            "{\"Country\":\"阿尔巴尼亚\",\"AreaCode\":\"00355\"},\n" +
            "{\"Country\":\"马耳他\",\"AreaCode\":\"00356\"},\n" +
            "{\"Country\":\"塞浦路斯\",\"AreaCode\":\"00357\"},\n" +
            "{\"Country\":\"芬兰\",\"AreaCode\":\"00358\"},\n" +
            "{\"Country\":\"保加利亚\",\"AreaCode\":\"00359\"},\n" +
            "{\"Country\":\"匈牙利\",\"AreaCode\":\"00336\"},\n" +
            "{\"Country\":\"德国\",\"AreaCode\":\"00349\"},\n" +
            "{\"Country\":\"南斯拉夫\",\"AreaCode\":\"00338\"},\n" +
            "{\"Country\":\"意大利\",\"AreaCode\":\"0039\"},\n" +
            "{\"Country\":\"圣马力诺\",\"AreaCode\":\"00223\"},\n" +
            "{\"Country\":\"梵蒂冈\",\"AreaCode\":\"00396\"},\n" +
            "{\"Country\":\"罗马尼亚\",\"AreaCode\":\"0040\"},\n" +
            "{\"Country\":\"瑞士\",\"AreaCode\":\"0041\"},\n" +
            "{\"Country\":\"列支敦士登\",\"AreaCode\":\"004175\"},\n" +
            "{\"Country\":\"奥地利\",\"AreaCode\":\"0043\"},\n" +
            "{\"Country\":\"英国\",\"AreaCode\":\"0044\"},\n" +
            "{\"Country\":\"丹麦\",\"AreaCode\":\"0045\"},\n" +
            "{\"Country\":\"瑞典\",\"AreaCode\":\"0046\"},\n" +
            "{\"Country\":\"挪威\",\"AreaCode\":\"0047\"},\n" +
            "{\"Country\":\"波兰\",\"AreaCode\":\"0048\"},\n" +
            "{\"Country\":\"埃及\",\"AreaCode\":\"0020\"},\n" +
            "{\"Country\":\"摩洛哥\",\"AreaCode\":\"00210\"},\n" +
            "{\"Country\":\"阿尔及利亚\",\"AreaCode\":\"00213\"},\n" +
            "{\"Country\":\"突尼斯\",\"AreaCode\":\"00216\"},\n" +
            "{\"Country\":\"利比亚\",\"AreaCode\":\"00218\"},\n" +
            "{\"Country\":\"冈比亚\",\"AreaCode\":\"00220\"},\n" +
            "{\"Country\":\"塞内加尔\",\"AreaCode\":\"00221\"},\n" +
            "{\"Country\":\"毛里塔尼亚\",\"AreaCode\":\"00222\"},\n" +
            "{\"Country\":\"马里\",\"AreaCode\":\"00223\"},\n" +
            "{\"Country\":\"几内亚\",\"AreaCode\":\"00224\"},\n" +
            "{\"Country\":\"科特迪瓦\",\"AreaCode\":\"00225\"},\n" +
            "{\"Country\":\"布基拉法索\",\"AreaCode\":\"00226\"},\n" +
            "{\"Country\":\"尼日尔\",\"AreaCode\":\"00227\"},\n" +
            "{\"Country\":\"多哥\",\"AreaCode\":\"00228\"},\n" +
            "{\"Country\":\"贝宁\",\"AreaCode\":\"00229\"},\n" +
            "{\"Country\":\"毛里求斯\",\"AreaCode\":\"00230\"},\n" +
            "{\"Country\":\"利比里亚\",\"AreaCode\":\"00231\"},\n" +
            "{\"Country\":\"塞拉利昂\",\"AreaCode\":\"00232\"},\n" +
            "{\"Country\":\"加纳\",\"AreaCode\":\"00233\"},\n" +
            "{\"Country\":\"尼日利亚\",\"AreaCode\":\"00234\"},\n" +
            "{\"Country\":\"乍得\",\"AreaCode\":\"00235\"},\n" +
            "{\"Country\":\"中非\",\"AreaCode\":\"00236\"},\n" +
            "{\"Country\":\"喀麦隆\",\"AreaCode\":\"00237\"},\n" +
            "{\"Country\":\"佛得角\",\"AreaCode\":\"00238\"},\n" +
            "{\"Country\":\"圣多美\",\"AreaCode\":\"00239\"},\n" +
            "{\"Country\":\"普林西比\",\"AreaCode\":\"00239\"},\n" +
            "{\"Country\":\"赤道几内亚\",\"AreaCode\":\"00240\"},\n" +
            "{\"Country\":\"加蓬\",\"AreaCode\":\"00241\"},\n" +
            "{\"Country\":\"刚果\",\"AreaCode\":\"00242\"},\n" +
            "{\"Country\":\"扎伊尔\",\"AreaCode\":\"00243\"},\n" +
            "{\"Country\":\"安哥拉\",\"AreaCode\":\"00244\"},\n" +
            "{\"Country\":\"几内亚比绍\",\"AreaCode\":\"00245\"},\n" +
            "{\"Country\":\"阿森松\",\"AreaCode\":\"00247\"},\n" +
            "{\"Country\":\"塞舌尔\",\"AreaCode\":\"00248\"},\n" +
            "{\"Country\":\"苏丹\",\"AreaCode\":\"00249\"},\n" +
            "{\"Country\":\"卢旺达\",\"AreaCode\":\"00250\"},\n" +
            "{\"Country\":\"埃塞俄比亚\",\"AreaCode\":\"00251\"},\n" +
            "{\"Country\":\"索马里\",\"AreaCode\":\"00252\"},\n" +
            "{\"Country\":\"吉布提\",\"AreaCode\":\"00253\"},\n" +
            "{\"Country\":\"肯尼亚\",\"AreaCode\":\"00254\"},\n" +
            "{\"Country\":\"坦桑尼亚\",\"AreaCode\":\"00255\"},\n" +
            "{\"Country\":\"乌干达\",\"AreaCode\":\"00256\"},\n" +
            "{\"Country\":\"布隆迪\",\"AreaCode\":\"00257\"},\n" +
            "{\"Country\":\"莫桑比克\",\"AreaCode\":\"00258\"},\n" +
            "{\"Country\":\"赞比亚\",\"AreaCode\":\"00260\"},\n" +
            "{\"Country\":\"马达加斯加\",\"AreaCode\":\"00261\"},\n" +
            "{\"Country\":\"留尼旺岛\",\"AreaCode\":\"00262\"},\n" +
            "{\"Country\":\"津巴布韦\",\"AreaCode\":\"00263\"},\n" +
            "{\"Country\":\"纳米比亚\",\"AreaCode\":\"00264\"},\n" +
            "{\"Country\":\"马拉维\",\"AreaCode\":\"00265\"},\n" +
            "{\"Country\":\"莱索托\",\"AreaCode\":\"00266\"},\n" +
            "{\"Country\":\"博茨瓦纳\",\"AreaCode\":\"00267\"},\n" +
            "{\"Country\":\"斯威士兰\",\"AreaCode\":\"00268\"},\n" +
            "{\"Country\":\"科摩罗\",\"AreaCode\":\"00269\"},\n" +
            "{\"Country\":\"南非\",\"AreaCode\":\"0027\"},\n" +
            "{\"Country\":\"圣赫勒拿\",\"AreaCode\":\"00290\"},\n" +
            "{\"Country\":\"阿鲁巴岛\",\"AreaCode\":\"00297\"},\n" +
            "{\"Country\":\"法罗群岛\",\"AreaCode\":\"00298\"},\n" +
            "{\"Country\":\"美国\",\"AreaCode\":\"001\"},\n" +
            "{\"Country\":\"加拿大\",\"AreaCode\":\"001\"},\n" +
            "{\"Country\":\"中途岛\",\"AreaCode\":\"001808\"},\n" +
            "{\"Country\":\"夏威夷\",\"AreaCode\":\"001808\"},\n" +
            "{\"Country\":\"威克岛\",\"AreaCode\":\"001808\"},\n" +
            "{\"Country\":\"安圭拉岛\",\"AreaCode\":\"001809\"},\n" +
            "{\"Country\":\"维尔京群岛\",\"AreaCode\":\"001809\"},\n" +
            "{\"Country\":\"圣卢西亚\",\"AreaCode\":\"001809\"},\n" +
            "{\"Country\":\"波多黎各\",\"AreaCode\":\"001809\"},\n" +
            "{\"Country\":\"牙买加\",\"AreaCode\":\"001809\"},\n" +
            "{\"Country\":\"巴哈马\",\"AreaCode\":\"001809\"},\n" +
            "{\"Country\":\"巴巴多斯\",\"AreaCode\":\"001809\"},\n" +
            "{\"Country\":\"阿拉斯加\",\"AreaCode\":\"001907\"},\n" +
            "{\"Country\":\"格陵兰岛\",\"AreaCode\":\"00299\"},\n" +
            "{\"Country\":\"福克兰群岛\",\"AreaCode\":\"00500\"},\n" +
            "{\"Country\":\"伯利兹\",\"AreaCode\":\"00501\"},\n" +
            "{\"Country\":\"危地马拉\",\"AreaCode\":\"00502\"},\n" +
            "{\"Country\":\"萨尔瓦多\",\"AreaCode\":\"00503\"},\n" +
            "{\"Country\":\"洪都拉斯\",\"AreaCode\":\"00504\"},\n" +
            "{\"Country\":\"尼加拉瓜\",\"AreaCode\":\"00505\"},\n" +
            "{\"Country\":\"哥斯达黎加\",\"AreaCode\":\"00506\"},\n" +
            "{\"Country\":\"巴拿马\",\"AreaCode\":\"00507\"},\n" +
            "{\"Country\":\"海地\",\"AreaCode\":\"00509\"},\n" +
            "{\"Country\":\"秘鲁\",\"AreaCode\":\"0051\"},\n" +
            "{\"Country\":\"墨西哥\",\"AreaCode\":\"0052\"},\n" +
            "{\"Country\":\"古巴\",\"AreaCode\":\"0053\"},\n" +
            "{\"Country\":\"阿根廷\",\"AreaCode\":\"0054\"},\n" +
            "{\"Country\":\"巴西\",\"AreaCode\":\"0055\"},\n" +
            "{\"Country\":\"智利\",\"AreaCode\":\"0056\"},\n" +
            "{\"Country\":\"哥伦比亚\",\"AreaCode\":\"0057\"},\n" +
            "{\"Country\":\"委内瑞拉\",\"AreaCode\":\"0058\"},\n" +
            "{\"Country\":\"玻利维亚\",\"AreaCode\":\"00591\"},\n" +
            "{\"Country\":\"圭亚那\",\"AreaCode\":\"00592\"},\n" +
            "{\"Country\":\"厄瓜多尔\",\"AreaCode\":\"00593\"},\n" +
            "{\"Country\":\"法属圭亚那\",\"AreaCode\":\"00594\"},\n" +
            "{\"Country\":\"巴拉圭\",\"AreaCode\":\"00595\"},\n" +
            "{\"Country\":\"马提尼克\",\"AreaCode\":\"00596\"},\n" +
            "{\"Country\":\"苏里南\",\"AreaCode\":\"00597\"},\n" +
            "{\"Country\":\"乌拉圭\",\"AreaCode\":\"00598\"},\n" +
            "{\"Country\":\"澳大利亚\",\"AreaCode\":\"0061\"},\n" +
            "{\"Country\":\"新西兰\",\"AreaCode\":\"0064\"},\n" +
            "{\"Country\":\"关岛\",\"AreaCode\":\"00671\"},\n" +
            "{\"Country\":\"科科斯岛\",\"AreaCode\":\"006722\"},\n" +
            "{\"Country\":\"诺福克岛\",\"AreaCode\":\"006723\"},\n" +
            "{\"Country\":\"圣诞岛\",\"AreaCode\":\"006724\"},\n" +
            "{\"Country\":\"瑙鲁\",\"AreaCode\":\"00674\"},\n" +
            "{\"Country\":\"汤加\",\"AreaCode\":\"00676\"},\n" +
            "{\"Country\":\"所罗门群岛\",\"AreaCode\":\"00677\"},\n" +
            "{\"Country\":\"瓦努阿图\",\"AreaCode\":\"00678\"},\n" +
            "{\"Country\":\"斐济\",\"AreaCode\":\"00679\"},\n" +
            "{\"Country\":\"科克群岛\",\"AreaCode\":\"00682\"},\n" +
            "{\"Country\":\"纽埃岛\",\"AreaCode\":\"00683\"},\n" +
            "{\"Country\":\"东萨摩亚\",\"AreaCode\":\"00684\"},\n" +
            "{\"Country\":\"西萨摩亚\",\"AreaCode\":\"00685\"},\n" +
            "{\"Country\":\"基里巴斯\",\"AreaCode\":\"00686\"},\n" +
            "{\"Country\":\"图瓦卢\",\"AreaCode\":\"00688\"}\n" +
            "]";
}
